DROP TABLE IF EXISTS urls CASCADE;
DROP TABLE IF EXISTS url_checks;

CREATE TABLE urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

ALTER TABLE urls
    ADD PRIMARY KEY (id);

CREATE TABLE url_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    status_code integer,
    title VARCHAR(255),
    h1 VARCHAR(255),
    description TEXT,
    url_Id BIGINT REFERENCES urls (id) NOT NULL,
    created_at TIMESTAMP
);

ALTER TABLE url_checks
    ADD PRIMARY KEY (id);
